### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by stevenschmatz** [tatsuyaokubo/dqn#4]
I'm getting this when cloning and running on Python 3.6.1, TensorFlow 1.2.1.

```
Using TensorFlow backend.
[2017-08-18 00:10:05,170] Making new env: Breakout-v0
dqn.py:90: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (8, 8), activation="relu", input_shape=(4, 84, 84..., strides=(4, 4))`
  model.add(Convolution2D(32, 8, 8, subsample=(4, 4), activation='relu', input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT)))
Traceback (most recent call last):
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/Users/schmatz/anaconda/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 8 from 4 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,4,84,84], [8,8,84,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dqn.py", line 312, in <module>
    main()
  File "dqn.py", line 275, in main
    agent = Agent(num_actions=env.action_space.n)
  File "dqn.py", line 58, in __init__
    self.s, self.q_values, q_network = self.build_network()
  File "dqn.py", line 90, in build_network
    model.add(Convolution2D(32, 8, 8, subsample=(4, 4), activation='relu', input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT)))
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/keras/models.py", line 436, in add
    layer(x)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3156, in conv2d
    data_format='NHWC')
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/schmatz/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 8 from 4 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,4,84,84], [8,8,84,32].
```

**Comment by a920604a** [comment]
i have the same problem

**Comment by Exception4U** [comment]
same problem ... filter size should not be greater than input layer size on which filter is applied  ... @tokb23 please highlight this issue

**Comment by Exception4U** [comment]
this problem has to do with input convention of input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT) @a920604a 

option is to change keras.json file to following configuration

{
    "image_dim_ordering": "th", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "tensorflow"
}

**Comment by huiofficial** [comment]
Changing keras.json still doesn't work for me. @Exception4U
