### ISSUE TITLE
error in running dqn and ddqn

### ISSUE THREAD

**Issue by Exception4U** [tatsuyaokubo/dqn#5]
python ddqn.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Using TensorFlow backend.
[2017-09-21 01:21:23,391] Making new env: Breakout-v0
ddqn.py:90: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (8, 8), strides=(4, 4), activation="relu", input_shape=(4, 84, 84...)`
  model.add(Convolution2D(32, 8, 8, subsample=(4, 4), activation='relu', input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT)))
Traceback (most recent call last):
  File "ddqn.py", line 314, in <module>
    main()
  File "ddqn.py", line 277, in main
    agent = Agent(num_actions=env.action_space.n)
  File "ddqn.py", line 58, in __init__
    self.s, self.q_values, q_network = self.build_network()
  File "ddqn.py", line 90, in build_network
    model.add(Convolution2D(32, 8, 8, subsample=(4, 4), activation='relu', input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT)))
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/keras/models.py", line 442, in add
    layer(x)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3164, in conv2d
    data_format='NHWC')
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 640, in convolution
    op=op)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 309, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 632, in op
    name=name)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 130, in _non_atrous_convolution
    name=name)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/tushar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 8 from 4 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,4,84,84], [8,8,84,32].

**Comment by huiofficial** [comment]
run into the same error with dqn.py, any idea? @Exception4U @tokb23

**Comment by Exception4U** [comment]
I think updating ur keras API should solve problem 
pip install --upgrade keras

**Comment by huiofficial** [comment]
As I upgraded, I still have the same error:
raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 8 from 4 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,4,84,84], [8,8,84,32].
@Exception4U

**Comment by Exception4U** [comment]
Ohhh !!! in that can you post your ~/.kerasrc file?

‌

**Comment by Exception4U** [comment]
sorry actually ~/.keras/keras.json this file



‌

**Comment by impulsecorp** [comment]
I get that same error, even after I change my keras.json file to
{
"image_dim_ordering": "th",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"

**Comment by Exception4U** [comment]
May be you refer here
<https://stackoverflow.com/questions/41651628/negative-dimension-size-caused-by-subtracting-3-from-1-for-conv2d>
and change function call



‌

**Comment by Exception4U** [comment]
parallelly I would encourage to use this fork as original author did not merge pull request.

https://github.com/Exception4U/dqn-1

**Comment by ShanHaoYu** [comment]
just did the above mentioned : 

from keras import backend as K
K.set_image_dim_ordering('th')

and it works for me :)
